name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: purescript-contrib/setup-purescript@main
        with:
          purescript: "0.15.0"
          spago: "0.20.9"
          psa: "0.8.2"
          purs-tidy: "latest"

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
          path: |
            .spago
            output

      - name: Build source
        run: spago build --purs-args '--censor-lib --strict'

      - name: Run tests
        run: spago test

      - name: Check formatting
        run: npm run check

      - name: Parse package sets
        run: npm run parse-package-set

      - name: Run file benchmark
        run: npm run bench-file src/PureScript/CST/Parser.purs
